# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script:
      npm install sfdx-cli --global
  displayName: 'Install Salesforce CLI'

- script:
      echo 'Y'| sfdx plugins:install sfdx-git-delta
  displayName: 'Install Git Delta'
- script:
  sfdx force:auth:sfdxurl:store $(DevAuthURL) -s -a DEV --instanceurl $(TestLogin)


